package UI;

import Model.Proxy;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Point;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author matut
 */
public class EasyRestoInterface extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public EasyRestoInterface() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.changeComponentVisibility(this.mainPanel, false);
        this.changeComponentVisibility(this.adminBackgroundPanel, false);
        this.changeComponentVisibility(this.workerPasswordPanel, false);
        this.proxy.getWorkerNameIDButton();
        this.changeComponentVisibility(this.familyScrollPanel, false);
        this.changeComponentVisibility(this.productScrollPanel, false);
        this.changeComponentVisibility(productScrollPanel,false);
        this.changeComponentVisibility(this.tableProductsScroll, false);
        this.changeComponentVisibility(this.billButtonsPanel, false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clockOutDialog = new javax.swing.JDialog();
        clockOutDialogPanel = new javax.swing.JPanel();
        clockOutDialogLabel = new javax.swing.JLabel();
        confirmClockOutButton = new javax.swing.JButton();
        refuseClockOutButton = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        tableMapPanel = new javax.swing.JPanel();
        tableProductsScroll = new javax.swing.JScrollPane();
        tableProducts = new javax.swing.JTable();
        billButtonsPanel = new javax.swing.JPanel();
        sendProductsButton = new javax.swing.JButton();
        deleteProductButton = new javax.swing.JButton();
        chargeButton = new javax.swing.JButton();
        printBillButton = new javax.swing.JButton();
        familyScrollPanel = new javax.swing.JScrollPane();
        familyPanel = new javax.swing.JPanel();
        productScrollPanel = new javax.swing.JScrollPane();
        productsPanel = new javax.swing.JPanel();
        ScrollBackButton = new javax.swing.JButton();
        clockOutButton = new javax.swing.JButton();
        tableIDLabel = new javax.swing.JLabel();
        tableLabel = new javax.swing.JLabel();
        mainPanelBackButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        productPriceLabel = new javax.swing.JLabel();
        workerPasswordPanel = new javax.swing.JPanel();
        passwordButtonPanelTextField = new javax.swing.JPasswordField();
        enterPasswordLabel = new javax.swing.JLabel();
        workerLoginButton = new javax.swing.JButton();
        workerNameLabel = new javax.swing.JLabel();
        passwordPanelBackButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        workerIDLabel = new javax.swing.JLabel();
        workerBackgroundPanel = new javax.swing.JPanel();
        workerScrollPanel = new javax.swing.JScrollPane();
        workersPanel = new javax.swing.JPanel();
        adminSettingsButton = new javax.swing.JButton();
        adminBackgroundPanel = new javax.swing.JPanel();
        adminPanel = new javax.swing.JPanel();
        loginTitleLabel = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        passTextField = new javax.swing.JPasswordField();
        passLabel = new javax.swing.JLabel();
        admingLoginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        adminPanelBackButton = new javax.swing.JButton();
        backgroundPanel = new javax.swing.JPanel();

        clockOutDialog.setSize(new java.awt.Dimension(400, 300));
        clockOutDialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockOutDialogPanel.setBackground(new java.awt.Color(0, 112, 115));
        clockOutDialogPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clockOutDialogLabel.setBackground(new java.awt.Color(255, 255, 255));
        clockOutDialogLabel.setForeground(new java.awt.Color(255, 255, 255));
        clockOutDialogLabel.setText("QUIERES REGISTRAR TU HORA DE SALIDA?");
        clockOutDialogPanel.add(clockOutDialogLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 260, 20));

        confirmClockOutButton.setText("SI");
        confirmClockOutButton.setBorder(null);
        confirmClockOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmClockOutButtonActionPerformed(evt);
            }
        });
        clockOutDialogPanel.add(confirmClockOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 60, 20));

        refuseClockOutButton.setText("NO");
        refuseClockOutButton.setBorder(null);
        refuseClockOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refuseClockOutButtonActionPerformed(evt);
            }
        });
        clockOutDialogPanel.add(refuseClockOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 60, 20));

        clockOutDialog.getContentPane().add(clockOutDialogPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 280));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(910, 840));
        setSize(new java.awt.Dimension(950, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(0, 112, 115));
        mainPanel.setMinimumSize(new java.awt.Dimension(900, 800));
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 800));
        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMapPanel.setBackground(new java.awt.Color(255, 255, 255));
        tableMapPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        mainPanel.add(tableMapPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 860, 700));
        tableMapPanel.getAccessibleContext().setAccessibleDescription("");

        tableProducts.setBackground(new java.awt.Color(255, 255, 255));
        tableProducts.setForeground(new java.awt.Color(0, 0, 0));
        tableProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableProducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableProducts.setRowSelectionAllowed(false);
        tableProducts.setSelectionBackground(new java.awt.Color(0, 153, 153));
        tableProducts.setSelectionForeground(new java.awt.Color(0, 0, 0));
        tableProductsScroll.setViewportView(tableProducts);
        tableProducts.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        mainPanel.add(tableProductsScroll, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 380, 410));

        billButtonsPanel.setBackground(new java.awt.Color(0, 112, 115));
        billButtonsPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sendProductsButton.setText("ENVIAR");
        sendProductsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendProductsButtonActionPerformed(evt);
            }
        });
        billButtonsPanel.add(sendProductsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        deleteProductButton.setText("BORRAR");
        deleteProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductButtonActionPerformed(evt);
            }
        });
        billButtonsPanel.add(deleteProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        chargeButton.setText("COBRAR");
        chargeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeButtonActionPerformed(evt);
            }
        });
        billButtonsPanel.add(chargeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        printBillButton.setText("IMPR.");
        printBillButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printBillButtonActionPerformed(evt);
            }
        });
        billButtonsPanel.add(printBillButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 80, -1));

        mainPanel.add(billButtonsPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 380, 60));

        familyScrollPanel.setBackground(new java.awt.Color(0, 112, 115));
        familyScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        familyScrollPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));

        familyPanel.setBackground(new java.awt.Color(0, 112, 115));
        familyPanel.setForeground(new java.awt.Color(102, 102, 102));
        familyPanel.setPreferredSize(new java.awt.Dimension(10, 1000));
        familyPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        familyScrollPanel.setViewportView(familyPanel);

        mainPanel.add(familyScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 360, 410));

        productScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        productScrollPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));

        productsPanel.setBackground(new java.awt.Color(0, 112, 115));
        productsPanel.setPreferredSize(new java.awt.Dimension(10, 1000));
        productsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        productScrollPanel.setViewportView(productsPanel);

        mainPanel.add(productScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, 360, 410));

        ScrollBackButton.setForeground(new java.awt.Color(51, 51, 51));
        ScrollBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/1.png"))); // NOI18N
        ScrollBackButton.setBorder(null);
        ScrollBackButton.setPreferredSize(new java.awt.Dimension(60, 60));
        ScrollBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScrollBackButtonActionPerformed(evt);
            }
        });
        mainPanel.add(ScrollBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 460, 65, 65));

        clockOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/shutdown.png"))); // NOI18N
        clockOutButton.setBorder(null);
        clockOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clockOutButtonActionPerformed(evt);
            }
        });
        mainPanel.add(clockOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 730, 65, 65));

        tableIDLabel.setBackground(new java.awt.Color(255, 255, 255));
        tableIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(tableIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 60, 30));

        tableLabel.setBackground(new java.awt.Color(255, 255, 255));
        tableLabel.setForeground(new java.awt.Color(255, 255, 255));
        tableLabel.setText("MESA:");
        mainPanel.add(tableLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 60, 30));

        mainPanelBackButton.setForeground(new java.awt.Color(51, 51, 51));
        mainPanelBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/1.png"))); // NOI18N
        mainPanelBackButton.setBorder(null);
        mainPanelBackButton.setPreferredSize(new java.awt.Dimension(60, 60));
        mainPanelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainPanelBackButtonActionPerformed(evt);
            }
        });
        mainPanel.add(mainPanelBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 65, 65));

        priceLabel.setForeground(new java.awt.Color(255, 255, 255));
        priceLabel.setText("PRECIO:");
        mainPanel.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 16, 50, 20));

        productPriceLabel.setForeground(new java.awt.Color(255, 255, 255));
        mainPanel.add(productPriceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 11, 80, 30));

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));

        workerPasswordPanel.setBackground(new java.awt.Color(0, 112, 115));
        workerPasswordPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        passwordButtonPanelTextField.setBackground(new java.awt.Color(255, 255, 255));
        passwordButtonPanelTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordButtonPanelTextFieldActionPerformed(evt);
            }
        });
        workerPasswordPanel.add(passwordButtonPanelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 190, -1));

        enterPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterPasswordLabel.setText("CONTRASEÑA:");
        workerPasswordPanel.add(enterPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 180, -1));

        workerLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        workerLoginButton.setText("LOGIN");
        workerLoginButton.setBorder(null);
        workerLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workerLoginButtonActionPerformed(evt);
            }
        });
        workerPasswordPanel.add(workerLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, 70, 20));

        workerNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        workerNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        workerNameLabel.setText("      WORKER");
        workerPasswordPanel.add(workerNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 260, 50));

        passwordPanelBackButton.setForeground(new java.awt.Color(51, 51, 51));
        passwordPanelBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/1.png"))); // NOI18N
        passwordPanelBackButton.setBorder(null);
        passwordPanelBackButton.setPreferredSize(new java.awt.Dimension(60, 60));
        passwordPanelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPanelBackButtonActionPerformed(evt);
            }
        });
        workerPasswordPanel.add(passwordPanelBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 65, 65));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID:");
        workerPasswordPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 20, -1));

        workerIDLabel.setForeground(new java.awt.Color(255, 255, 255));
        workerIDLabel.setText("000000");
        workerPasswordPanel.add(workerIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 100, -1));

        getContentPane().add(workerPasswordPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));

        workerBackgroundPanel.setBackground(new java.awt.Color(0, 112, 115));
        workerBackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workerScrollPanel.setBackground(new java.awt.Color(0, 122, 115));
        workerScrollPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        workerScrollPanel.setPreferredSize(new java.awt.Dimension(1000, 1000));

        workersPanel.setBackground(new java.awt.Color(255, 255, 255));
        workersPanel.setMaximumSize(new java.awt.Dimension(420, 610));
        workersPanel.setPreferredSize(new java.awt.Dimension(420, 2000));
        workersPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
        workerScrollPanel.setViewportView(workersPanel);

        workerBackgroundPanel.add(workerScrollPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 450, 610));

        adminSettingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/admin.png"))); // NOI18N
        adminSettingsButton.setPreferredSize(new java.awt.Dimension(60, 60));
        adminSettingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminSettingsButtonActionPerformed(evt);
            }
        });
        workerBackgroundPanel.add(adminSettingsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 65, 65));

        getContentPane().add(workerBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));

        adminBackgroundPanel.setBackground(new java.awt.Color(0, 112, 115));
        adminBackgroundPanel.setAutoscrolls(true);
        adminBackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminPanel.setBackground(new java.awt.Color(0, 112, 115));
        adminPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginTitleLabel.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        loginTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginTitleLabel.setText("EASYRESTO");
        adminPanel.add(loginTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, 35));

        emailTextField.setBackground(new java.awt.Color(255, 255, 255));
        emailTextField.setForeground(new java.awt.Color(0, 0, 0));
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        adminPanel.add(emailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 210, -1));

        emailLabel.setForeground(new java.awt.Color(255, 255, 255));
        emailLabel.setText("EMAIL");
        adminPanel.add(emailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        passTextField.setBackground(new java.awt.Color(255, 255, 255));
        passTextField.setForeground(new java.awt.Color(0, 0, 0));
        passTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTextFieldActionPerformed(evt);
            }
        });
        adminPanel.add(passTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 210, -1));

        passLabel.setForeground(new java.awt.Color(255, 255, 255));
        passLabel.setText("PASS");
        adminPanel.add(passLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 40, -1));

        admingLoginButton.setForeground(new java.awt.Color(51, 51, 51));
        admingLoginButton.setText("LOGIN");
        admingLoginButton.setBorder(null);
        admingLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admingLoginButtonActionPerformed(evt);
            }
        });
        adminPanel.add(admingLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 80, 20));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" ADMIN ZONE");
        adminPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 80, 30));

        adminBackgroundPanel.add(adminPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 370, 450));

        adminPanelBackButton.setForeground(new java.awt.Color(255, 255, 255));
        adminPanelBackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/img/1.png"))); // NOI18N
        adminPanelBackButton.setBorder(null);
        adminPanelBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminPanelBackButtonActionPerformed(evt);
            }
        });
        adminBackgroundPanel.add(adminPanelBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 65, 65));

        getContentPane().add(adminBackgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));

        backgroundPanel.setBackground(new java.awt.Color(0, 112, 115));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(900, 800));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(900, 800));
        backgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admingLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admingLoginButtonActionPerformed
        this.proxy.adminSettingsLogin(this.emailTextField.getText(), this.passTextField.getPassword());
        this.emptyPassFieldText(this.passTextField);
    }//GEN-LAST:event_admingLoginButtonActionPerformed

    private void passTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTextFieldActionPerformed
        this.proxy.adminSettingsLogin(this.emailTextField.getText(), this.passTextField.getPassword());
        this.emptyPassFieldText(this.passTextField);
    }//GEN-LAST:event_passTextFieldActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        this.passTextField.requestFocusInWindow();
    }//GEN-LAST:event_emailTextFieldActionPerformed

    private void passwordButtonPanelTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordButtonPanelTextFieldActionPerformed
        this.workerLoginButtonActionPerformed(evt);
    }//GEN-LAST:event_passwordButtonPanelTextFieldActionPerformed

    private void workerLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workerLoginButtonActionPerformed
        if (this.proxy.workerLogin(this.workerIDLabel.getText(), this.passwordButtonPanelTextField.getPassword())) {
            if (!this.proxy.checkClockIn(this.proxy.getWorkerLogged().getId())) {
                this.proxy.clockIn(this.proxy.getWorkerLogged().getId());
            }
            this.changeComponentVisibility(this.workerPasswordPanel, false);
            this.changeComponentVisibility(this.mainPanel, true);
            this.tableMapPanel.removeAll();
            this.proxy.getTablesButton();
        }
        this.emptyPassFieldText(this.passwordButtonPanelTextField);
    }//GEN-LAST:event_workerLoginButtonActionPerformed

    private void passwordPanelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPanelBackButtonActionPerformed
        this.changeComponentVisibility(this.workerPasswordPanel, false);
        this.changeComponentVisibility(this.workerBackgroundPanel, true);
        this.changeComponentVisibility(this.workersPanel, true);
        this.emptyPassFieldText(this.passwordButtonPanelTextField);
        this.changeComponentVisibility(this.adminSettingsButton, true);

    }//GEN-LAST:event_passwordPanelBackButtonActionPerformed

    private void adminPanelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminPanelBackButtonActionPerformed
        this.changeComponentVisibility(this.adminBackgroundPanel, false);
        this.changeComponentVisibility(this.workerBackgroundPanel, true);
        this.emailTextField.setText("");
        this.emptyPassFieldText(passTextField);

    }//GEN-LAST:event_adminPanelBackButtonActionPerformed

    private void adminSettingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminSettingsButtonActionPerformed
        this.changeComponentVisibility(this.workerBackgroundPanel, false);
        this.changeComponentVisibility(this.adminBackgroundPanel, true);
    }//GEN-LAST:event_adminSettingsButtonActionPerformed

    private void ScrollBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScrollBackButtonActionPerformed
        if (this.productScrollPanel.isVisible()) {
            this.changeComponentVisibility(this.productScrollPanel, false);
            this.changeComponentVisibility(this.familyScrollPanel, true);
            this.productPriceLabel.setText("");
        }
    }//GEN-LAST:event_ScrollBackButtonActionPerformed

    private void clockOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clockOutButtonActionPerformed
        this.clockOutDialog.setLocationRelativeTo(this);
        this.changeComponentVisibility(this.clockOutDialog, true);
    }//GEN-LAST:event_clockOutButtonActionPerformed

    private void confirmClockOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmClockOutButtonActionPerformed
        this.proxy.clockOut(this.proxy.getWorkerLogged().getId());
        JOptionPane.showMessageDialog(this, "HASTA PRONTO!");
        this.changeComponentVisibility(this.mainPanel, false);
        this.changeComponentVisibility(this.clockOutDialog, false);
        this.changeComponentVisibility(this.workerBackgroundPanel, true);
        this.changeComponentVisibility(this.workersPanel, true);
    }//GEN-LAST:event_confirmClockOutButtonActionPerformed

    private void refuseClockOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refuseClockOutButtonActionPerformed
        this.changeComponentVisibility(this.clockOutDialog, false);
    }//GEN-LAST:event_refuseClockOutButtonActionPerformed

    private void mainPanelBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainPanelBackButtonActionPerformed
         if (this.proxy.rememberClockOut(this.proxy.getWorkerLogged().getId())) {
            JOptionPane.showMessageDialog(this, "RECUERDA REGISTRAR TU SALIDA!");
        }
        if (this.tableMapPanel.isVisible()) {
            this.changeComponentVisibility(this.mainPanel, false);
            this.changeComponentVisibility(this.workerBackgroundPanel, true);
            this.changeComponentVisibility(this.workersPanel, true);
        } else {
            this.changeComponentVisibility(this.tableMapPanel, true);
            this.changeComponentVisibility(this.familyScrollPanel, false);
            this.changeComponentVisibility(this.productScrollPanel, false);
            this.changeComponentVisibility(this.tableProductsScroll, false);
            this.productPriceLabel.setText("");
            this.changeComponentVisibility(this.billButtonsPanel, false);
        }
    }//GEN-LAST:event_mainPanelBackButtonActionPerformed

    private void sendProductsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendProductsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendProductsButtonActionPerformed

    private void deleteProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteProductButtonActionPerformed

    private void chargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeButtonActionPerformed

    private void printBillButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printBillButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_printBillButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EasyRestoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EasyRestoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EasyRestoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EasyRestoInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new EasyRestoInterface().setVisible(true);
            }
        });
    }

    /**
     *
     * @param panel
     * @param button
     */
    private void addButtonToPanel(JPanel panel, JButton button) {
        panel.add(button);
    }
    public void configProductButton(String productName, double price){
        JButton productButton = new JButton(productName);
        productButton.setPreferredSize(new Dimension(80,80));
        this.addActionListenerToProductButton(productButton, productName, price);
        this.addButtonToPanel(this.productsPanel, productButton);
        
    }
    private void addActionListenerToProductButton(JButton button, String productName, double price){
        DefaultTableModel tableModel = (DefaultTableModel) this.tableProducts.getModel();
        button.addActionListener(new ActionListener(){
        String[] productData = {productName, Double.toString(price)};
            @Override
            public void actionPerformed(ActionEvent e) {
               productPriceLabel.setText(Double.toString(price));
               tableModel.addRow(productData);
            }
            
        });
    }
    public void configProductFamilyButton(String familyName) {
        JButton familyProductButton = new JButton(familyName);
        familyProductButton.setPreferredSize(new Dimension(80, 80));
        this.addActionListenerToFamilyProductButton(familyProductButton, familyName);
        this.addButtonToPanel(this.familyPanel, familyProductButton);
        
    }
    
    
  
    private void addActionListenerToFamilyProductButton(JButton button,String familyName){
        button.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                changeComponentVisibility(familyScrollPanel,false);
                changeComponentVisibility(productScrollPanel,true);
//                changeComponentVisibility(productsPanel,true);
                productsPanel.removeAll();
                proxy.getProductButton(familyName);
                
            }
        });
    }
    
    public void configWorkerButton(String workerName, int workerID) {
        JButton workerButton = new JButton(workerName);
        workerButton.setPreferredSize(new Dimension(80, 80));
        this.addActionListenerToWorkerButton(workerButton, workerID, workerName);
        this.addButtonToPanel(this.workersPanel, workerButton);
    }

    private void addActionListenerToWorkerButton(JButton button, int workerID, String workerName) {
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                changeComponentVisibility(workersPanel, false);
                changeComponentVisibility(workerPasswordPanel, true);
                changeComponentVisibility(workerBackgroundPanel, false);
                configWorkerNameLabel(workerName);
                configWorkerIDLabel(workerID);
                passwordButtonPanelTextField.requestFocus();
                changeComponentVisibility(adminSettingsButton, true);
                
            }
        });
    }

    public void configTableButton(int tableID, Point tableLocation, int capacity, String url) {
        JButton tableButton = new JButton();
        Dimension buttonDimension = configButtonDimensionByCapacity(capacity);

        JLabel tableNumberLabel = configTableIDLabel(tableID);
        Point tableButtonCenterPoint = new Point(tableLocation.x + buttonDimension.width / 2, tableLocation.y + buttonDimension.height / 2);

        tableButton.setIcon(getResizedButtonIcon(url, buttonDimension));
        hideButtonBackground(tableButton);

        addActionListenerToTableButton(tableButton, tableID);

        this.tableMapPanel.add(tableNumberLabel, new AbsoluteConstraints(tableButtonCenterPoint.x - tableNumberLabel.getWidth() / 2, tableButtonCenterPoint.y - tableNumberLabel.getHeight() / 2));
        this.tableMapPanel.add(tableButton, new AbsoluteConstraints(tableLocation.x, tableLocation.y, buttonDimension.width, buttonDimension.height));
    }

    private void addActionListenerToTableButton(JButton tableButton, int tableID) {
        tableButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tableIDLabel.setText(String.valueOf(tableID));
                changeComponentVisibility(tableMapPanel, false);
                changeComponentVisibility(tableProductsScroll, true);
                changeComponentVisibility(familyScrollPanel,true);
                changeComponentVisibility(productScrollPanel,false);
                changeComponentVisibility(billButtonsPanel, true);
                familyPanel.removeAll();
                proxy.getProductFamilyButton();
            }
        });
    }

    private JLabel configTableIDLabel(int tableID) {
        JLabel tableNumberLabel = new JLabel(String.valueOf(tableID));
        tableNumberLabel.setSize(10, 15);
        return tableNumberLabel;
    }

    private ImageIcon getResizedButtonIcon(String iconUrl, Dimension buttonDimension) {
        ImageIcon icon = new ImageIcon(iconUrl);
        Image img = icon.getImage().getScaledInstance(buttonDimension.width, buttonDimension.height, Image.SCALE_SMOOTH);
        return new ImageIcon(img);
    }

    private void hideButtonBackground(JButton tableButton) {
        tableButton.setContentAreaFilled(false);
        tableButton.setBorderPainted(false);
    }

    private Dimension configButtonDimensionByCapacity(int capacity) {

        if (capacity == 2) {
            return new Dimension(60, 60);
        } else if (capacity == 4) {
            return new Dimension(60, 60);
        } else if (capacity == 6) {
            return new Dimension(120, 60);
        } else {
            return new Dimension(100, 100);
        }
    }

    private void configWorkerIDLabel(int workerID) {
        workerIDLabel.setText(String.valueOf(workerID));
    }

    private void configWorkerNameLabel(String workerName) {
        workerNameLabel.setText(workerName);
        workerNameLabel.setHorizontalAlignment(JLabel.CENTER);
    }

    private void changeComponentVisibility(Component component, boolean visibility) {
        component.setVisible(visibility);
    }

    public void emptyPassFieldText(JPasswordField passwordField) {
        passwordField.setText("");
    }

    public boolean checkEmptyWorkerPassField(String password) throws HeadlessException {
        return password.isBlank();
    }

    public boolean checkEmptyAdminLoginFields(String email, String password) throws HeadlessException {
        return password.isBlank() || email.isBlank();
    }

    public Proxy getProxy() {
        return proxy;
    }

    public void setProxy(Proxy proxy) {
        this.proxy = proxy;
    }

    public JPanel getAdminBackgroundPanel() {
        return adminBackgroundPanel;
    }

    public void setAdminBackgroundPanel(JPanel adminBackgroundPanel) {
        this.adminBackgroundPanel = adminBackgroundPanel;
    }

    public JPanel getAdminPanel() {
        return adminPanel;
    }

    public void setAdminPanel(JPanel adminPanel) {
        this.adminPanel = adminPanel;
    }

    public JButton getAdminPanelBackButton() {
        return adminPanelBackButton;
    }

    public void setAdminPanelBackButton(JButton adminPanelBackButton) {
        this.adminPanelBackButton = adminPanelBackButton;
    }

    public JButton getAdminSettingsButton() {
        return adminSettingsButton;
    }

    public void setAdminSettingsButton(JButton adminSettingsButton) {
        this.adminSettingsButton = adminSettingsButton;
    }

    public JButton getAdmingLoginButton() {
        return admingLoginButton;
    }

    public void setAdmingLoginButton(JButton admingLoginButton) {
        this.admingLoginButton = admingLoginButton;
    }

    public JButton getClockOutButton() {
        return clockOutButton;
    }

    public void setClockOutButton(JButton clockOutButton) {
        this.clockOutButton = clockOutButton;
    }

    public JDialog getClockOutDialog() {
        return clockOutDialog;
    }

    public void setClockOutDialog(JDialog clockOutDialog) {
        this.clockOutDialog = clockOutDialog;
    }

    public JLabel getClockOutDialogLabel() {
        return clockOutDialogLabel;
    }

    public void setClockOutDialogLabel(JLabel clockOutDialogLabel) {
        this.clockOutDialogLabel = clockOutDialogLabel;
    }

    public JPanel getClockOutDialogPanel() {
        return clockOutDialogPanel;
    }

    public void setClockOutDialogPanel(JPanel clockOutDialogPanel) {
        this.clockOutDialogPanel = clockOutDialogPanel;
    }

    public JButton getConfirmClockOutButton() {
        return confirmClockOutButton;
    }

    public void setConfirmClockOutButton(JButton confirmClockOutButton) {
        this.confirmClockOutButton = confirmClockOutButton;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return workerScrollPanel;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.workerScrollPanel = jScrollPane1;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    public JButton getMainPanelBackButton() {
        return ScrollBackButton;
    }

    public void setMainPanelBackButton(JButton mainPanelBackButton) {
        this.ScrollBackButton = mainPanelBackButton;
    }

    public JButton getRefuseClockOutButton() {
        return refuseClockOutButton;
    }

    public void setRefuseClockOutButton(JButton refuseClockOutButton) {
        this.refuseClockOutButton = refuseClockOutButton;
    }

    public JPanel getTableMapPanel() {
        return tableMapPanel;
    }

    public void setTableMapPanel(JPanel tableMapPanel) {
        this.tableMapPanel = tableMapPanel;
    }

    public JPanel getWorkerBackgroundPanel() {
        return workerBackgroundPanel;
    }

    public void setWorkerBackgroundPanel(JPanel workerBackgroundPanel) {
        this.workerBackgroundPanel = workerBackgroundPanel;
    }

    public JLabel getWorkerIDLabel() {
        return workerIDLabel;
    }

    public void setWorkerIDLabel(JLabel workerIDLabel) {
        this.workerIDLabel = workerIDLabel;
    }

    public JButton getWorkerLoginButton() {
        return workerLoginButton;
    }

    public void setWorkerLoginButton(JButton workerLoginButton) {
        this.workerLoginButton = workerLoginButton;
    }

    public JPanel getWorkerPasswordPanel() {
        return workerPasswordPanel;
    }

    public void setWorkerPasswordPanel(JPanel workerPasswordPanel) {
        this.workerPasswordPanel = workerPasswordPanel;
    }

    public JPanel getWorkersPanel() {
        return workersPanel;
    }

    public void setWorkersPanel(JPanel workersPanel) {
        this.workersPanel = workersPanel;
    }

    public JPanel getBackgroundPanel() {
        return adminBackgroundPanel;
    }

    public void setBackgroundPanel(JPanel backgroundPanel) {
        this.adminBackgroundPanel = backgroundPanel;
    }

    public JLabel getEmailLabel() {
        return emailLabel;
    }

    public void setEmailLabel(JLabel emailLabel) {
        this.emailLabel = emailLabel;
    }

    public JTextField getEmailTextField() {
        return emailTextField;
    }

    public void setEmailTextField(JTextField emailTextField) {
        this.emailTextField = emailTextField;
    }

    public JButton getLoginButton() {
        return admingLoginButton;
    }

    public void setLoginButton(JButton loginButton) {
        this.admingLoginButton = loginButton;
    }

    public JPanel getLoginButtonsPanel() {
        return workersPanel;
    }

    public void setLoginButtonsPanel(JPanel loginButtonsPanel) {
        this.workersPanel = loginButtonsPanel;
    }

    public JPanel getLoginPanel() {
        return adminPanel;
    }

    public void setLoginPanel(JPanel loginPanel) {
        this.adminPanel = loginPanel;
    }

    public JLabel getLoginTitleLabel() {
        return loginTitleLabel;
    }

    public void setLoginTitleLabel(JLabel loginTitleLabel) {
        this.loginTitleLabel = loginTitleLabel;
    }

    public JLabel getPassLabel() {
        return passLabel;
    }

    public void setPassLabel(JLabel passLabel) {
        this.passLabel = passLabel;
    }

    public JPasswordField getPassTextField() {
        return passTextField;
    }

    public void setPassTextField(JPasswordField passTextField) {
        this.passTextField = passTextField;
    }

    public JLabel getEnterPasswordLabel() {
        return enterPasswordLabel;
    }

    public void setEnterPasswordLabel(JLabel enterPasswordLabel) {
        this.enterPasswordLabel = enterPasswordLabel;
    }

    public JButton getLoginButton2() {
        return workerLoginButton;
    }

    public void setLoginButton2(JButton loginButton2) {
        this.workerLoginButton = loginButton2;
    }

    public JPanel getPasswordButtonPanel() {
        return workerPasswordPanel;
    }

    public void setPasswordButtonPanel(JPanel passwordButtonPanel) {
        this.workerPasswordPanel = passwordButtonPanel;
    }

    public JPasswordField getPasswordButtonPanelTextField() {
        return passwordButtonPanelTextField;
    }

    public void setPasswordButtonPanelTextField(JPasswordField passwordButtonPanelTextField) {
        this.passwordButtonPanelTextField = passwordButtonPanelTextField;
    }

    public JButton getPasswordPanelBackButton() {
        return passwordPanelBackButton;
    }

    public void setPasswordPanelBackButton(JButton passwordPanelBackButton) {
        this.passwordPanelBackButton = passwordPanelBackButton;
    }

    public JLabel getWorkerNameLabel() {
        return workerNameLabel;
    }

    public void setWorkerNameLabel(JLabel workerNameLabel) {
        this.workerNameLabel = workerNameLabel;
    }

    private Proxy proxy = new Proxy(this);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ScrollBackButton;
    private javax.swing.JPanel adminBackgroundPanel;
    private javax.swing.JPanel adminPanel;
    private javax.swing.JButton adminPanelBackButton;
    private javax.swing.JButton adminSettingsButton;
    private javax.swing.JButton admingLoginButton;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel billButtonsPanel;
    private javax.swing.JButton chargeButton;
    private javax.swing.JButton clockOutButton;
    private javax.swing.JDialog clockOutDialog;
    private javax.swing.JLabel clockOutDialogLabel;
    private javax.swing.JPanel clockOutDialogPanel;
    private javax.swing.JButton confirmClockOutButton;
    private javax.swing.JButton deleteProductButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JLabel enterPasswordLabel;
    private javax.swing.JPanel familyPanel;
    private javax.swing.JScrollPane familyScrollPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel loginTitleLabel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton mainPanelBackButton;
    private javax.swing.JLabel passLabel;
    private javax.swing.JPasswordField passTextField;
    private javax.swing.JPasswordField passwordButtonPanelTextField;
    private javax.swing.JButton passwordPanelBackButton;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JButton printBillButton;
    private javax.swing.JLabel productPriceLabel;
    private javax.swing.JScrollPane productScrollPanel;
    private javax.swing.JPanel productsPanel;
    private javax.swing.JButton refuseClockOutButton;
    private javax.swing.JButton sendProductsButton;
    private javax.swing.JLabel tableIDLabel;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JPanel tableMapPanel;
    private javax.swing.JTable tableProducts;
    private javax.swing.JScrollPane tableProductsScroll;
    private javax.swing.JPanel workerBackgroundPanel;
    private javax.swing.JLabel workerIDLabel;
    private javax.swing.JButton workerLoginButton;
    private javax.swing.JLabel workerNameLabel;
    private javax.swing.JPanel workerPasswordPanel;
    private javax.swing.JScrollPane workerScrollPanel;
    private javax.swing.JPanel workersPanel;
    // End of variables declaration//GEN-END:variables
}
